name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v3

      - name: Running Test
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: src
          package-manager: yarn
          test-script: yarn test:coverage
          annotations: none
