name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: testCoverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: src
          package-manager: yarn
          test-script: yarn test:coverage
          annotations: none
          output: report-markdown

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
